In [3]:
## algunos ejercicios con pandas y Glottolog :)

import pandas as pd

In [4]:
## https://glottolog.org/meta/downloads

languoids = pd.read_csv('languoid.csv',sep=',')

In [5]:
languoids

,id,family_id,parent_id,name,bookkeeping,level,latitude,longitude,iso639P3code,description,markup_description,child_family_count,child_language_count,child_dialect_count,country_ids
0,3adt1234,afro1255,nort3292,3Ad-Tekles,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
1,aala1237,aust1307,ramo1244,Aalawa,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
2,aant1238,nucl1709,nort2920,Aantantara,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
3,aari1238,sout2845,ahkk1235,Aari-Gayil,False,family,NaN,NaN,aiz,NaN,NaN,0,2,0,NaN
4,aari1239,sout2845,aari1238,Aari,False,language,5.95034,36.5721,aiw,NaN,NaN,0,0,0,ET
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25434,zuti1239,tupi1275,guaj1255,Guajajára of Zutiua,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
25435,zuwa1238,koia1260,omie1241,Zuwadza,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
25436,zwal1238,atla1278,shal1242,Zwall,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
25437,zyph1238,sino1245,nucl1757,Zyphe,False,language,22.52400,93.2640,zyp,NaN,NaN,0,0,2,IN MM
25438,zyud1238,ural1272,komi1269,Zyuzdin,False,dialect,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN

Para comenzar filtre **languoids**, es decir pode filas innecesarias, usando solamente lenguas de sudamérica. Una forma es usar datos analizados en la clase 4 :) Recuerde qué almacena el diccionario **macroarea**. Recomendación: guárdelo en pickle y lealo acá :)

Construya un diccionario **glottocode:family_id**

Construya un diccionario **iso:family_id**

Construya un diccionario **family_id:lista de códigos glottocode pertenecientes a family_id**. Filtrar el diccionario por lenguas de América del Sur. Guardar el diccionario como pickle.

Use el diccionario anterior para calcular el **número de familias que tienen un número X de lenguas**

**Grafique en dos dimensiones** la información anterior :)

¿Cuántas lenguas posee la familia **quec1387?** Use **languoid[languoid['family_id']='quec1387']**

Use las columnas **latitude y longitude** para crear un gráfico que ubique cada lengua en un plano de dos dimensiones